/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface MonoSpikeResult {
  pid: number
  monoModuleName: string
  monoModuleBase: string
  monoModuleSize: number
  peMachine: string
  peSubsystem: string
  monoGetRootDomainRva: string
  monoGetRootDomainVa: string
  monoGetRootDomainFirstBytes: string
  globalRootDomainAddr: string
  disasmPattern: string
  rootDomainPtr: string
  domainAssembliesPtr: string
  loadedImagesPtr: string
  elapsedMicros: number
  notes: Array<string>
}

export declare function spikeLocateMono(): Promise<MonoSpikeResult>
