/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AccountIdResult {
  hi: number
  lo: number
}

export interface ArenaInfoResult {
  deck: DeckResult
  wins: number
  losses: number
}

export interface BattlegroundRatingInfoResult {
  rating: number
  rank: number
}

export interface BattleTagResult {
  name: string
  fullBattleTag: string
}

export interface BoardEntity {
  entityId: number
  cardId: string
  zonePosition: number
  attack: number
  health: number
  damage: number
}

export interface BoardStateResult {
  friendly: Array<BoardEntity>
  opposing: Array<BoardEntity>
}

export interface CardResult {
  dbfId: number
  count: number
  premium: number
}

export interface ChoiceCard {
  entityId: number
  cardId: string
}

export interface ChoiceGroup {
  sourceEntityId: number
  countMin: number
  countMax: number
  cards: Array<ChoiceCard>
}

export interface ChoicesResult {
  mulligan?: ChoiceGroup
  general?: ChoiceGroup
}

/**
 * Structured diagnostic surfaced to JS consumers. Mirrors `CollectionCounters`
 * but with napi-compatible field types (`i32` instead of `usize`/`u128`).
 */
export interface CollectionDiagnostic {
  listSize: number
  parsed: number
  nonZeroDbfid: number
  nullPtrs: number
  fieldMisses: number
  sampleClass?: string
  elapsedMs: number
}

export interface DeckCardResult {
  cardId: string
  count: number
  premium: number
}

export interface DeckResult {
  id: number
  name: string
  hero: string
  formatType: number
  deckType: number
  seasonId: number
  cardbackId: number
  createDateMicrosec: number
  cards: Array<DeckCardResult>
}

export interface DeckStateResult {
  friendlyDeck: Array<InMatchDeckCard>
  opposingDeckCount: number
}

export interface GameServerInfoResult {
  address: string
  port: number
  gameHandle: number
  clientHandle: number
  version: string
  spectatorMode: boolean
  mission: number
  spectatorPassword: string
  auroraPassword: string
}

export interface GameTypeResult {
  /**
   * Numeric value of the `PegasusShared.GameType` enum, or `null`
   * when the GameMgr service is not registered (very early startup).
   */
  gameType?: number
  /**
   * `PegasusShared.FormatType` enum value (1=Wild, 2=Standard,
   * 3=Classic, 4=Twist).
   */
  formatType?: number
  /** Mission/scenario id, `null` when not in a mission. */
  missionId?: number
}

export declare function getAccountId(): Promise<AccountIdResult | null>

export declare function getArenaDeck(): Promise<ArenaInfoResult | null>

export declare function getBattlegroundRatingInfo(): Promise<BattlegroundRatingInfoResult | null>

export declare function getBattleTag(): Promise<BattleTagResult | null>

export declare function getBoardState(): Promise<BoardStateResult | null>

/** Diagnostic: PID the current cached runtime is bound to, or `0` if none. */
export declare function getBoundPid(): Promise<number>

export declare function getChoices(): Promise<ChoicesResult | null>

export declare function getCollection(): Promise<Array<CardResult> | null>

export declare function getCollectionDiagnostic(): Promise<CollectionDiagnostic>

export declare function getDecks(): Promise<Array<DeckResult> | null>

export declare function getDeckState(): Promise<DeckStateResult | null>

export declare function getEditedDeck(): Promise<DeckResult | null>

export declare function getGameType(): Promise<GameTypeResult | null>

export declare function getHandState(): Promise<HandStateResult | null>

export declare function getHearthstoneWindow(): Promise<HearthstoneWindowResult | null>

export declare function getMatchInfo(): Promise<MatchInfoResult | null>

export declare function getMedalInfo(): Promise<MedalInfoResult | null>

export declare function getOpponentSecrets(): Promise<OpponentSecretsResult | null>

/**
 * Diagnostic: number of times the slot has populated a fresh runtime.
 * Resets to 0 on Electron process restart. Surfaced via napi for the
 * `dump_reflection` example and any future debug overlay.
 */
export declare function getReinitCount(): Promise<number>

export declare function getSelectedDeckId(): Promise<SelectedDeckResult | null>

export declare function getServerInfo(): Promise<GameServerInfoResult | null>

export interface HandCard {
  entityId: number
  cardId: string
  zonePosition: number
}

export interface HandStateResult {
  friendlyHand: Array<HandCard>
  opposingHandCount: number
}

export interface HearthstoneWindowResult {
  x: number
  y: number
  width: number
  height: number
  minimized: boolean
  visible: boolean
  foreground: boolean
}

export interface InMatchDeckCard {
  entityId: number
  cardId: string
}

export declare function isAlive(): Promise<boolean>

export declare function isGameOver(): Promise<boolean>

export declare function isMulligan(): Promise<IsMulliganResult>

export interface IsMulliganResult {
  mulligan?: boolean
}

export declare function isSpectating(): Promise<boolean>

export interface MatchInfoResult {
  localPlayer?: MatchPlayerResult
  opposingPlayer?: MatchPlayerResult
  missionId: number
  gameType: number
  formatType: number
  /**
   * Reserved season-id slots — populated by a follow-up MedalInfo
   * translator wiring (currently 0).
   */
  rankedSeasonId: number
  arenaSeasonId: number
  brawlSeasonId: number
}

export interface MatchPlayerResult {
  /** In-match player id (== TAG_CONTROLLER value). */
  id: number
  /** Display name (BattleTag for human, AI name for vs-AI). */
  name: string
  /**
   * `Player.m_side` enum value (1=friendly, 2=opposing per
   * Hearthstone protocol).
   */
  side: number
  /** Per-format ranks reserved for follow-up MedalInfo wiring. */
  standardRank: number
  standardLegendRank: number
  wildRank: number
  wildLegendRank: number
  classicRank: number
  classicLegendRank: number
  twistRank: number
  twistLegendRank: number
  /** Cardback id (PegasusUtil.NetCacheCardBacks). */
  cardbackId: number
}

export interface MedalInfoData {
  leagueId: number
  starLevel: number
  stars: number
  streak: number
  legendRank: number
  seasonId: number
  seasonWins: number
  bestStarLevel: number
}

export interface MedalInfoResult {
  wild?: MedalInfoData
  standard?: MedalInfoData
  classic?: MedalInfoData
  twist?: MedalInfoData
}

export interface OpponentSecretsResult {
  secrets: Array<SecretEntity>
  count: number
}

export declare function placeWindowAboveHearthstone(nativeWindowHandle: Buffer): boolean

export interface SecretEntity {
  entityId: number
  cardId: string
  zonePosition: number
}

export interface SelectedDeckResult {
  /** Saved-deck id (>0 when the user picked a custom CollectionDeck). */
  deckId: number
  /**
   * Template-deck id (>0 when the user picked a Blizzard template).
   * Mutually exclusive with `deck_id` in practice.
   */
  templateDeckId: number
  /** Currently visible format tab — `PegasusShared.FormatType` enum. */
  formatType: number
}

export declare function subscribeHearthstoneWindowEvents(callback: (() => void)): number

export declare function unsubscribeHearthstoneWindowEvents(subscriptionId: number): boolean
