/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AccountIdResult {
  hi: number
  lo: number
}

export interface ArenaInfoResult {
  deck: DeckResult
  wins: number
  losses: number
}

export interface BattlegroundRatingInfoResult {
  rating: number
  rank: number
}

export interface BattleTagResult {
  name: string
  fullBattleTag: string
}

export interface CardResult {
  dbfId: number
  count: number
  premium: number
}

export interface DeckCardResult {
  dbfId: number
  count: number
  premium: number
}

export interface DeckResult {
  id: number
  name: string
  hero: string
  formatType: number
  deckType: number
  cards: Array<DeckCardResult>
}

export declare function dumpClass(className: string): Promise<Array<FieldDumpEntry>>

export interface FieldDumpEntry {
  name: string
  offset: number
}

export interface GameServerInfoResult {
  address: string
  port: number
  mission: number
  gameHandle: number
  version: string
  resumable: boolean
}

export declare function getAccountId(): Promise<AccountIdResult | null>

export declare function getArenaDeck(): Promise<ArenaInfoResult | null>

export declare function getBattlegroundRatingInfo(): Promise<BattlegroundRatingInfoResult | null>

export declare function getBattleTag(): Promise<BattleTagResult | null>

export declare function getCollection(): Promise<Array<CardResult> | null>

export declare function getDecks(): Promise<Array<DeckResult> | null>

export declare function getGameType(): Promise<number>

export declare function getMatchInfo(): Promise<MatchInfoResult | null>

export declare function getMedalInfo(): Promise<MedalInfoResult | null>

export declare function getServerInfo(): Promise<GameServerInfoResult | null>

export declare function isAlive(): Promise<boolean>

export declare function isGameOver(): Promise<boolean>

export declare function isMulligan(): Promise<boolean | null>

export declare function isSpectating(): Promise<boolean>

export declare function listServices(): Promise<Array<ServiceEntry>>

export interface MatchInfoResult {
  localPlayer: MatchPlayerResult
  opposingPlayer: MatchPlayerResult
  missionId: number
  gameType: number
  formatType: number
}

export interface MatchPlayerResult {
  id: number
  name: string
  accountIdHi: number
  accountIdLo: number
  battleTagName: string
  battleTagFull: string
  standardRank: number
  wildRank: number
  classicRank: number
  twistRank: number
}

export interface MedalInfoData {
  leagueId: number
  starLevel: number
  stars: number
  legendRank: number
  seasonId: number
  seasonWins: number
}

export interface MedalInfoResult {
  standard?: MedalInfoData
  wild?: MedalInfoData
  classic?: MedalInfoData
  twist?: MedalInfoData
}

export interface ServiceEntry {
  name: string
  addr: number
}
