/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function spikeReadMz(): Promise<SpikeResult>

export interface SpikeResult {
  pid: number
  baseAddress: string
  headerHex: string
  elapsedMicros: number
}
